export const LOGIN_USER = 'LOGIN_USER';
export const GET_USER = 'GET_USER';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const ERROR = 'ERROR';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const CREATE_CATEGORIES = 'GET_CATEGORIES';
